### ISSUE TITLE
Possible problem with KeystoneV3Authenticator token renewal

### ISSUE THREAD

**Issue by AlainEdwards** [stefanodefaria/swift-client#16]
Hi,

**What:**
Correct me if I am wrong but I believe the correct way to check if a token has expired is to check the `currentToken.expires` property rather than the `currentToken.expires_at` property since the currentToken.expires_at is a string and not a Date object. Yes? Also it doesn't exist in the returned JSON object.

Link to the line number in question below.
https://github.com/stefanodefaria/swift-client/blob/e910473b56c7d681f10f152032ffdc10bd0b5a74/KeystoneV3Authenticator.js#L91

**How:**
I came across this problem because I noticed after about 1 hour my keystone token expired and was being rejected by Openstack services. After checking my code and my cloud, I thought I would check this module. As it turns out I noticed the expires_at property is being referenced  but the object that is being returned only has an `expires` property.

Love the module btw. Thanks in advance.

**Comment by AlainEdwards** [comment]
Created a PR incase this does end up being the case.

https://github.com/stefanodefaria/swift-client/pull/17

**Comment by stefanodefaria** [comment]
PR merged.
