### ISSUE TITLE
Cannot login - authenticated: false

### ISSUE THREAD

**Issue by dfaustryjak** [stefanodefaria/swift-client#2]
I wrote this line in python -> swift -A http://private.owncloud/auth/v1.0/ -U mylogin -K mypass list mycontainer <-

and everything is working... 

now i try use your proposition:
const SwiftClient = require('openstack-swift-client');
let client = new SwiftClient('https://privete.owncloud/auth/v1.0/', 'mylogin', 'mypass');
and it can't authenticate:
 authenticated: false,
     url: null,
     token: null

**Comment by stefanodefaria** [comment]
In version 1.1.1, authentication was done in a lazy way. That means your Swift client will only perform an authentication request upon a Swift operation (list, create container, put object, etc.), and not after its instantiation.

Try this:

```js
const SwiftClient = require('openstack-swift-client');
let client = new SwiftClient('https://privete.owncloud/auth/v1.0/', 'mylogin', 'mypass');
client.list().then((list) => { console.log('Done authenticating\n', client, '\n', list); });
```
And see if *client* has authenticated.

Ps.: I updated *openstack-swift-client* (> 1.1.2) to start the authentication process at instantiation time.
Note that you may perform a Swift operation before authentication is complete, however it will transparently wait until your Swift client is authenticated;

**Comment by dfaustryjak** [comment]
Ok thanks for quick response. When I configured for example cyberduck i remember that one of the parameters was the path to the container. Can you told me where Can I setup this parameter ?

**Comment by stefanodefaria** [comment]
What do you mean?

If you want to make operations within a container, you first need get the container object from your Swift client, using the method *SwiftClient.container(name)*. All you need to provide is the container name.

For more info, please refer to https://github.com/stefanodefaria/swift-client#swiftclientcontainername .

**Comment by dfaustryjak** [comment]
I mean, in the folder 'my_root_folder' I have another folders of all months. How can I list the contents of 'my_root_folder'?

**Comment by dfaustryjak** [comment]
Now i have something like this:
const SwiftClient = require('openstack-swift-client');
let client = new SwiftClient('http://my_private_server.com', 'my_login', 'my_pass');

client.list().then((list) => {
    console.log('Done authenticating\n',
    client, '\n', list); });

And i have still the same message 404 -NOTFOUND

**Comment by stefanodefaria** [comment]
1- Can you check which version of *openstack-swift-client* you are using?
2- Post your output for the code below. **DO NOT FORGET TO HIDE YOUR CREDENTIALS IN YOUR COMMENT.**

```js
client.list().then((list) => {  console.log('Done authenticating\n',client, '\n', list); }).catch(err => console.log(err));
```

**Comment by dfaustryjak** [comment]
https://pastebin.com/aVnTt0Aq  I replace server ip username and password

**Comment by stefanodefaria** [comment]
That's weird, it says _Not Found: The resource could not be found._
It's usually caused by inserting a wrong authentication URL.

Are you sure that your authurl, username and password are correct?
Check if command below returns HTTP/1.1 200 OK, along with a 'X-Auth-Token' and  a 'X-Storage-Url'.
```sh
curl -i -H "X-Auth-User: username" -H "X-Auth-Key: password" authurl
```

Please note that *openstack-swift-client* only supports v1 authentication for now (based on http headers).
Authentication v2 (based on json) is not yet supported.
For more info, check https://www.swiftstack.com/docs/cookbooks/swift_usage/auth.html.

**Comment by dfaustryjak** [comment]
HTTP/1.1 404 Not Found
Content-Length: 70
Content-Type: text/html; charset=UTF-8
X-Trans-Id: txddfd40b25b4a4eacb4791-0058e92f14
Date: Sat, 08 Apr 2017 18:42:28 GMT

I don't know why i have this code 404. :( because this command -> swift -A http://server-U username -K password list root_folder  <- is working

**Comment by dfaustryjak** [comment]
Ok i change the url and now i have 403 code :(.... I had the same problem in cyberduck because i don't change container to 'root_folder' How can i do this ?

**Comment by stefanodefaria** [comment]
About listing all files within a certain directory, you have to list all objects in a container.
Then you'll have to filter by object name, since files within a directory are objects whose names start with 'directory/'.

For example:

```js
const SwiftClient = require('openstack-swift-client');
let client = new SwiftClient('https://privete.owncloud/auth/v1.0/', 'mylogin', 'mypass');
let container = client.container('test-container');
let directoryWithinContainer = 'test-dir/';

container .list().then((list) => {
    let filesWithinDirectory = list.filter(item => item.name.indexOf(directoryWithinContainer) === 0);
    console.log(filesWithinDirectory);
});
```

**Comment by stefanodefaria** [comment]
403 code means 'Forbidden'.
You're probably providing the wrong Auth-URL or Username or Password.

**Comment by dfaustryjak** [comment]
Ok you told about listing all files but i need to have information about all directories. I must get All possibilities -> directoryWithinContainer -> 'test-dir/'. I set directoryWithinContainer to photo-master/holidays01/2015/ and i get all files (its working) but this sulution isn't good for me, i want to prepare json which all tree of directories in my server.

**Comment by dfaustryjak** [comment]
Maybe i schould prepare new issue :) ?

**Comment by stefanodefaria** [comment]
It isn't actually an issue, you'll just have to add up your own logic to build this JSON you need.

In Openstack Swift there are only two types of entity:
1- Container
2- Objects

There are no really 'directories' within containers. It's all a matter of path based on object name, like _\<dir1\>/\<dir2\>/file._
Checking for **content_type** may help you to tell if an Object is a directory or a file.

For example, I have the following file structure in my container:
```
(file) testfile1.txt
(dir) test-dir
    (file) test-dir/testfile2.txt
    (file) test-dir/testfile3.txt
```

And I get the following output

```js
[ { hash: '7215ee9c7d9dc229d2921a40e899ec5f',
    last_modified: '2017-04-08T18:35:56.348260',
    bytes: 1,
    name: 'test-dir',
    content_type: 'application/directory' },
  { hash: '818959a8b06ccb5667ff3d72c1284fcc',
    last_modified: '2017-04-08T18:36:51.341870',
    bytes: 9,
    name: 'test-dir/testfile2.txt',
    content_type: 'text/plain' },
  { hash: '818959a8b06ccb5667ff3d72c1284fcc',
    last_modified: '2017-04-08T18:37:06.221330',
    bytes: 9,
    name: 'test-dir/testfile3.txt',
    content_type: 'text/plain' },
  { hash: '818959a8b06ccb5667ff3d72c1284fcc',
    last_modified: '2017-04-08T18:36:33.023040',
    bytes: 9,
    name: 'testfile1.txt',
    content_type: 'text/plain' } ]
```

**Comment by stefanodefaria** [comment]
By the way, is your authentication problem resolved?

**Comment by dfaustryjak** [comment]
Yes :) ! Thank you very much ! Very rarely happens to someone responsible for me so fast. Thank you very much for your help again

**Comment by stefanodefaria** [comment]
No problem :)
