### ISSUE TITLE
Is it possible to increase the display limit?

### ISSUE THREAD

**Issue by dfaustryjak** [stefanodefaria/swift-client#4]
Hello again :)

I have little problem.. I list 'my_root_container' and i have more than 10 000 objects. So the question is -> Is it possible to increase the display limit? Or do you advise how I could set up a limit and filter the directories?

For example, I have a situation in which the pictures are placed in the directory my_root_foler / 1_folder / 1.jpg.

And I would like to make an array of all folders that are 2 positions after the -> '/' in this case '1_folder'. Unfortunately the listing stops at 10,000 items. And it does not finish me preparing a list of folders with 2 items

**Comment by stefanodefaria** [comment]
You are correct,[ Openstack documentation](https://developer.openstack.org/api-ref/object-storage/?expanded=list-activated-capabilities-detail,show-container-details-and-list-objects-detail#show-container-details-and-list-objects
) states that there is a limit of 10,000 items on a LIST operation.

To fetch remaining items, one must fill the _marker_ query parameter with the object name of the last item in the previous list result.

I'll add support to that as soon as I can.

**Comment by stefanodefaria** [comment]
Hello.

If you call the new method 'client.info()' you'll be able to read the value of 'container_listing_limit' for your cluster. It should be 10000 for you.

For listing objects in a container that has more than 10000 items, you will need to list it several times, using the _marker_ and _end_marker_ headers. [More info about listing objects in a container](https://developer.openstack.org/api-ref/object-storage/?expanded=show-object-metadata-detail,show-container-details-and-list-objects-detail#show-container-details-and-list-objects).

Please let me know if this solves your problem.

Regards,
Stéfano

**Comment by dfaustryjak** [comment]
Everything is working thank you again for help :)
