### ISSUE TITLE
How to execute function after download file ?

### ISSUE THREAD

**Issue by dfaustryjak** [stefanodefaria/swift-client#5]
Hi :)

Can you told me How can I execute function after file is downloaded?

container.get(remoteFilePath , writeStream).then(() =>
                                console.log('done downloading!')
                                load_actual_points(); <--- it doesn't work :( 
                            );

**Comment by stefanodefaria** [comment]
If your arrow function has more than one command, you will need to use brackets.

```js
container.get(remoteFilePath , writeStream).then(() =>{
console.log('done downloading!')
load_actual_points();
});
```

To find out more about arrow functions, check [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).
