### ISSUE TITLE
How to be sure the object was downloaded

### ISSUE THREAD

**Issue by dfaustryjak** [stefanodefaria/swift-client#6]
function download_photo(path,expo_id,callback){

    const fs = require('fs');
    const SwiftClient = require('openstack-swift-client');
    var mkdirp = require('mkdirp');
    mkdirp('./db/'+expo_id, function(err) {
        const client = secret ;)
        const localFilePath = './db/' + id + '/image.jpg';
        const remoteFilePath = path;
        const writeStream = fs.createWriteStream(localFilePath);
        const container = client.container('smarteye-cti');
        container.get(remoteFilePath, writeStream).then(() => console.log("OK")).done(callback());

    })
}

After doing this function I want to call the callback to know that the download was finished :) How can this be done? Can you help me :) ?

**Comment by stefanodefaria** [comment]
Within the 'then' function it should already be finished.
When you see 'ok' on your screen download is complete.

**Comment by dfaustryjak** [comment]
I think that we can close this issue :) The problem is due to computer malfunction
