### ISSUE TITLE
Update npm

### ISSUE THREAD

**Issue by simonschllng** [stefanodefaria/swift-client#9]
Could you publish KeystoneV3Authenticator to npm please? Thanks.

**Comment by stefanodefaria** [comment]
Sure, I'll do it when I get home

Em seg, 25 de jun de 2018 às 08:06, Simon <notifications@github.com>
escreveu:

**Comment by stefanodefaria** [comment]
Sorry I forgot to do it yesterday.
I'll do it today.

Em seg, 25 de jun de 2018 às 08:49, Stéfano Patti de Faria <
stefanodefaria@gmail.com> escreveu:
